import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} no-scrollbar `}>
        <main>
          {children}
          <div className="flex justify-center gap-4 text-xs items-center bg-white h-6 font-medium">
            <span>&copy; 2025</span>
            <span>
              Designed & Developed by{" "}
              <a
                href="https://brandontakuraportfolio.vercel.app"
                className="text-red-500 hover:underline"
              >
                takura_dev
              </a>
            </span>
          </div>
        </main>
      </body>
    </html>
  );
}
